  Source.cpp
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(290,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(290,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(298,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(298,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(301,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(301,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(307,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(307,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(310,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(310,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(313,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(313,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(319,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(319,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(326,2): error C2360: пропуск инициализации "x" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(283): message : см. объявление "x"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(326,2): error C2360: пропуск инициализации "arr" из-за метки "case"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(281): message : см. объявление "arr"
C:\Users\Саша\source\repos\hw\Homework3.1\task1\Source.cpp(334,12): warning C4244: аргумент: преобразование "time_t" в "unsigned int", возможна потеря данных
